FROM python:2.7-alpine

RUN apk add --update curl gcc g++ \
    && rm -rf /var/cache/apk/*

RUN ln -s /usr/include/locale.h /usr/include/xlocale.h

RUN pip install bottle numpy cython \
    && pip install pandas

COPY ./server.py /opt/

EXPOSE 8080 8080

ENTRYPOINT ["python", "/opt/server.py"]
