name: Build and push docker image to dockerhub

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'version to update release assets'
        default: 'v'
      repo:
        required: true
        description: 'target repository'
        type: choice
        options:
        - fake_sqs
        - dynamo-local-admin

env:
  DOCKERHUB_USER: evalphobia

jobs:
  main:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - name: Checkout all history
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout the version
      run: git checkout ${{ github.event.inputs.version }}
    - name: Set version
      id: set_version
      run: |
        VERSION=${{ github.event.inputs.version }}
        test -z "$VERSION" && echo "No version" && exit 1;
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Set repo
      id: set_repo
      run: |
        DOCKERHUB_REPO=${{ github.event.inputs.repo }}
        test -z "$DOCKERHUB_REPO" && echo "No target repository" && exit 1;
        TARGET_DOCKERDIR=${DOCKERHUB_REPO}/assets
        TARGET_DOCKERFILE=${TARGET_DOCKERDIR}/Dockerfile
        test -r "$TARGET_DOCKERFILE" || echo "No target Dockerfile on '${TARGET_DOCKERFILE}'"
        echo "DOCKERHUB_REPO=$DOCKERHUB_REPO" >> $GITHUB_ENV
        echo "TARGET_DOCKERDIR=$TARGET_DOCKERDIR" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./${{ env.TARGET_DOCKERDIR }}
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}:${{ env.VERSION }}
